data:
  data_dir: "imagenet_sketch"
  train_dir: "./data/train"
  test_dir: "./data/test"

model:
  name: "resnet-18"
  pretrained: true
  num_classes: 1000

training:
  batch_size: 32
  num_epochs: 30
  learning_rate: 0.001
  device: "cuda"
  criterion: "CrossEntropyLoss"
  optimizer:
    name: "Adam"
    weight_decay: 0.0001

paths:
  save_dir: "./saved_models"
  log_dir: "./logs"