data:
  data_dir: "imagenet_sketch"
  train_dir: "./data/train"
  train_info_file: "./data/train.csv"
  test_dir: "./data/test"
  test_info_file: "./data/test.csv"
  augmented_dir: "./data/augmented"
  augmented_info_file: "./data/augmented.csv"
model:
  name: "resnet"
  pretrained: True
  num_classes: 1000

training:
  mode : "train"
  batch_size: 16
  validation_ratio : 0.2
  num_epochs: 50
  additional_train: True
  additional_epochs: 5
  learning_rate: 0.0001939044801896184
  n_splits: 3
  device: "cuda"
  metric: "accuracy"
  drop_rate: 0.4461988529143907
  attn_drop_rate: 0.1665896935298184
  drop_rate_path: 0.05950492951303196
  growth_rate: 16
  compression_factor: 0.1


  criterion: "CrossEntropyLoss"
  optimizer:
    name: "Adam"
    weight_decay: 0.0001

  lr_scheduler:
    name: "ReduceLROnPlateau"
    factor: 0.1
    patience: 3
    min_lr: 1e-6
    monitor: 'metric'

  early_stopping:
    patience: 5
    min_delta: 0.001
    evidence: 'loss'
    monitor: 'metric'  

  augmentation:
    noise: 0.5
    blur : 0.5
offline_augmentation:
  augmentation:
    flip: 1
  ratio: 2

randaugment:
  num_ops: 3
  magnitude: 4

paths:
  save_dir: "./outputs/saved_models"
  log_dir: "./outputs/logs"
  output_dir: "./tests"

random_seed: 20010316

hyperparameter_optimization:
  n_trials: 30
  parameters:
    opt_learning_rate:
      min: 1e-5
      max: 1e-1
      type: "log_uniform"
    opt_batch_size:
      values: [16, 32, 64]
      type: "categorical"
    opt_num_epochs: 
      min: 5
      max: 20
      type: "int"
    opt_drop_rate:
      min: 0.0
      max: 0.5
      type: "uniform"
    attn_drop_rate: # For ViT
      min: 0.0
      max: 0.5
      type: "uniform"
    drop_path_rate: # For ConvNext
      min: 0.05
      max: 0.5
      type: "uniform"
    growth_rate: # For DenseNet
      values: [12, 24, 32, 48]
      type: "categorical"
    compression_factor: # For DenseNet
      min: 0.5
      max: 1.0
      type: "uniform"