data:
  data_dir: "imagenet_sketch"
  train_dir: "./data/train"
  test_dir: "./data/test"

model:
  name: "ViT"
  pretrained: true
  num_classes: 1000

training:
  batch_size: 32
  num_epochs: 30
  learning_rate: 0.001
  device: "cuda"
  criterion: "CrossEntropyLoss"
  optimizer:
    name: "Adam"
    weight_decay: 0.0001
  lr_scheduler:
    name: "ReduceLROnPlateau"
    factor: 0.1
    patience: 3
    min_lr: 1e-6
  early_stopping:
    patience: 5
    min_delta: 0.001

paths:
  save_dir: "./outputs/saved_models"
  log_dir: "./outputs/logs"